#!/bin/bash
#inkVerbRunner! verb.ink

# This installs the Vultr CLI API

# How to use:
## ./setup [API key]

# Eg:
## ./setup SOMELONGKEY

if [ -z "$1" ]; then
  /usr/bin/echo "Needs API key as argument, I quit."
  exit 0
fi

if [ ! -f  "/opt/rink/inst/setup" ]; then
  /usr/bin/echo "Not where I'm supposed to be, I quit."
  exit 0
fi

APIkey="$1"

# Runner permissions
/usr/bin/chmod 750 /opt/rink/run/*

# Prepare the directories
/usr/bin/mkdir -p /opt/rink/tmp
/usr/bin/mkdir -p /opt/rink/conf/verbers
/usr/bin/mkdir -p /opt/rink/conf/domains
/usr/bin/mkdir -p /opt/rink/conf/drives
/usr/bin/mkdir -p /opt/rink/conf/snapshots
/usr/bin/mkdir -p /opt/rink/conf/simple
/usr/bin/mkdir -p /opt/rink/conf/verbers.destroyed
/usr/bin/mkdir -p /opt/rink/conf/simple.destroyed
/usr/bin/mkdir -p /opt/rink/conf/drives.smashed
/usr/bin/mkdir -p /opt/rink/ns
/usr/bin/mkdir -p /opt/rink
/usr/bin/mkdir -p /opt/rink/snapshotid
/usr/bin/ln -sfn /opt/rink ~/

# API settings
/usr/bin/pacman -S vultr-cli --noconfirm
/usr/bin/cat <<EOF > /root/.vultr-cli.yaml
api-key: ${APIkey}
EOF
/usr/bin/vultr-cli instance list --config /root/.vultr-cli.yaml
export VULTR_API_KEY="${APIkey}"

# .ssh/config
/usr/bin/cat <<EOF >> /root/.ssh/config
# Managed automatically by inkVerb inker #
EOF

# Remove the inst directory
/usr/bin/rm -rf /opt/rink/inst

# Finish
/usr/bin/echo "Before adding any new vps instance via newvps, you must run: setsnapshot, setport & setkey"
