#!/bin/bash
#inkVerbRunner! verb.ink

##DEV IMPORTANT!
## This incompletely performs the same tastk as importvps
## However, this does some things more efficiently, such as via readvps
## This does not take into consideration that verb/conf/server* files have already been instantiated by setup
## TO-DO: Keep this for reference, eview and squash this with importvps, then delete this
##DEV IMPORTANT!

# This is the master command to add an existing Verber to be controlled by this Rink, complete with all requirements
## The Verber must have the Rink control keyes installed in authorized_keys and already have setup run
## The verb namespace or domain mod is irrelevant
## This merely adds the verber to the basic nameserver control Rink so that its DNS zone will be published through this NS Rink cluster

# How to use:
## ./addmodvps [namespace] [tld] [vultr instance ID] [user]

# Eg:
## ./addmodvps  name ink bla3-bla2-bla1 john
## ./addmodvps nameothername red bla0-bla0-bl4a john


if [ -z "$4" ]; then
  /usr/bin/echo "Needs namespace, TLD, Vultr instance ID, & user arguments, I quit."
  exit 0
fi

# Get our Rink-NS name settings
. /opt/rink/rinknames

namespace="$1"
VerbTLD="$2"
VultrInstanceID="$3"
vuser="$4"

. /opt/rink/portnum # for Port

# Read the VPS
if [ ! -f "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.raw" ]; then
  /opt/rink/run/readvps "$namespace" "$VerbTLD" "$VultrInstanceID" "$vuser"
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
fi

# Create new SSH keys on the new verber and install their pub keys on the NS servers
## This must go before verb/inst/setup or the server will deny access in post-setup ssh calls
if ! grep -q '^RinkKeys="DONE"' "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /opt/rink/run/newverbrinkkeys ${namespace} ${VerbTLD} ${vuser}
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  if [ "$?" = "0" ]; then
    /usr/bin/echo 'RinkKeys="DONE"' >> /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
  fi
fi

# Update to latest NS servers
if ! grep -q 'RinkKeys="DONE"' "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/ssh ${namespace}.${VerbTLD} /opt/verb/serfs/rinkupdatekeys
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  if [ "$?" = "0" ]; then
    /usr/bin/echo 'RinkKeys="DONE"' >> /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
  fi
fi
if ! grep -q 'RinkVerbsNSListed="DONE"' "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/ssh ${namespace}.${VerbTLD} /opt/verb/serfs/rinkupdateallverbs
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  if [ "$?" = "0" ]; then
    /usr/bin/echo 'RinkVerbsNSListed="DONE"' >> /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
  fi
fi

# Restart the mod Verber
/usr/bin/ssh ${namespace}.${VerbTLD} /usr/bin/reboot
