#!/bin/bash
#inkVerbRunner! verb.ink

# This lists a domain on the NS slave nameservers when it is hosted on this rink
## rinkadddomain defers to this when it leans that it is being run on a rink server
## This cannot use verb domains, which must be used by rinkupdateallverbs

# How to use:
## ./addmasterdomain [ domain.tld ]

# Eg:
## ./addmasterdomain inkisaverb.com


masterdomain=$1

# Configs
. /opt/verb/conf/servernameip
. /opt/rink/rinknames

# Already configured?
if [ "$RinkConfigured" != "rink" ]; then
	echo "This is not a Rink, something is very wrong"
	exit 6
fi

# Served or parked?
if [ -f "/opt/verb/conf/inkdns/zones/${masterdomain}" ]; then
  parkserve="served"
elif [ -f "/opt/verb/conf/inkdns/parked/${masterdomain}" ]; then
  parkserve="parked"
else
  /usr/bin/echo "${masterdomain} is neither served nor parked here; nothing to do"
  exit 8
fi

#DEV Alternate version of above
/usr/bin/ssh -T ${RinkNS1Name}.${RinkVerbTLD} <<EOS
/usr/bin/cat <<EOF > /srv/sns/${ServerName}-${ServerTLD}/domains/${parkserve}/${masterdomain}
sdnsDomain="${masterdomain}"
sdnsIPv4="${ServerIPv4}"
sdnsIPv4ARPA="${ServerARPAIPv4}"
sdnsIPv6Exp="${ServerExpIPv6}"
sdnsIPv6Cmp="${ServerIPv6}"
sdnsIPv6ARPA="${ServerARPAIPv6}"
EOF
EOS
/usr/bin/ssh -T ${RinkNS2Name}.${RinkVerbTLD} <<EOS
/usr/bin/cat <<EOF > /srv/sns/${ServerName}-${ServerTLD}/domains/${parkserve}/${masterdomain}
sdnsDomain="${masterdomain}"
sdnsIPv4="${ServerIPv4}"
sdnsIPv4ARPA="${ServerARPAIPv4}"
sdnsIPv6Exp="${ServerExpIPv6}"
sdnsIPv6Cmp="${ServerIPv6}"
sdnsIPv6ARPA="${ServerARPAIPv6}"
EOF
EOS

#DEV replaces the above code because above checks whether it is a served or parked domain
# Make the NS nameserver entries
# /usr/bin/ssh ${RinkNS1Name}.${RinkVerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${RinkVerbTLD} ${masterdomain} -n
# e="$?"; [[ "$e" = "0" ]] || exit "$e"
# /usr/bin/echo "addmasterdomain to added ${masterdomain} to NS1"
# /usr/bin/ssh ${RinkNS2Name}.${RinkVerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${RinkVerbTLD} ${masterdomain} -n
# e="$?"; [[ "$e" = "0" ]] || exit "$e"
# /usr/bin/echo "addmasterdomain to added ${masterdomain} to NS2"
