#!/bin/bash
#inkVerbRunner! verb.ink

# This simply checks the health of a VPS to see if all settings and variables are in place as they should be
## This is useful after running addvps for verber creation
## If healthy, this will exit 0 as true
## If not healthy, this will exit 6 as false (impossible error)


# How to use:
## ./checkvpshealth [verb-namespace] [tld] [user]

# Eg:
## ./checkvpshealth name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

# Defaults
. /opt/rink/rinknames

namespace="$1"
checkVerbTLD="$2"
vuser="$3"

# Check the existence of the verber
if [ ! -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.raw" ] && [ ! -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.vrb" ]; then
  /usr/bin/echo "No config files exist. Nothing to check."
  exit 8
elif [ ! -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.raw" ]; then
  /usr/bin/echo "No .raw file exists."
  /usr/bin/echo "Verber is not healthy!"
  exit 6
elif [ ! -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.vrb" ]; then
  /usr/bin/echo "No .vrb file exists."
  /usr/bin/echo "Verber is not healthy!"
  exit 6
fi

# Verify the instance ID and that the files indeed exist
if [ -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.vrb" ] && [ -f "/opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.raw" ]; then
  /usr/bin/echo "Check config for ${namespace}.${checkVerbTLD}"
  . /opt/rink/conf/verbers/${namespace}.${checkVerbTLD}.vrb
  . /opt/rink/ns/${VerbNameServersConfig}
  . /opt/rink/sshkey
  ## we can now use ${VultrInstanceID}
  RawVultrInstanceID="$(/usr/bin/cat /opt/rink/conf/verbers/${namespace}.${VerbTLD}.raw | /usr/bin/grep ^ID | /usr/bin/sed s"/ID\t\t\t//")"
  if [ "${RawVultrInstanceID}" != "${VultrInstanceID}" ]; then
    /usr/bin/echo ".raw and .vrb conf files conflict."
    /usr/bin/echo "Verber is not healthy!"
    exit 6
  fi
else
  /usr/bin/echo "Verber is not healthy!"
  exit 6
fi

# Check conf credentials
isIP4() {
local ip4="$1"
local vvar="$2"
local validregex="^([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})"
if [[ "${ip4}" =~ ${validregex} ]]; then
isIP4="true"; else
isIP4="false"; fi
}
## IP6
### Expanded or compressed IPv6 formats both work
isIP6() {
local ip6="$1"
local vvar="$2"
local validregex="(([0-9a-fA-F]{1,4}:){7,7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))"
if [[ "${ip6}" =~ ${validregex} ]]; then
isIP6="true"; else
isIP6="false"; fi
}
### Reverse IPv6
rarpa_ipv6() {
  local idx s=${1//:}
  for (( idx=${#s} - 1; idx>=0; idx-- )); do
    printf '%s.' "${s:$idx:1}"
  done
  printf 'ip6.arpa\n'
}

# Check VPS for responsiveness
## Abbreviated waitvpson
powerstatus="$(/usr/bin/vultr-cli instance get ${VultrInstanceID} | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
if [ "${powerstatus}" != "running" ]; then
    /usr/bin/vultr-cli instance restart ${VultrInstanceID}
    sleep 10
fi
## Check if responsive
/opt/rink/run/waitvpsanswer ${namespace} ${VerbTLD} poweronce
if [ "$?" != "0" ]; then
  /usr/bin/echo "Verber is not healthy!"
  exit 6
fi

# Conf file and settings
/usr/bin/echo "Check config settings"
if [ -z "${VultrInstanceID}" ]; then
  /usr/bin/echo "VultrInstanceID missing from conf."
  unhealthy="true"
fi
if [ -z "${VultrPlan}" ]; then
  /usr/bin/echo "VultrPlan missing from conf."
  unhealthy="true"
  if ! /usr/bin/vultr-cli plans list | /usr/bin/grep -q "^${VultrPlan}"; then
    /usr/bin/echo "Region invalid."
    unhealthy="true"
  fi
fi
if [ -z "${DateCreated}" ]; then
  /usr/bin/echo "DateCreated missing from conf."
  unhealthy="true"
fi
if [ -z "${VerbHostID}" ]; then
  /usr/bin/echo "VerbHostID missing from conf."
  unhealthy="true"
else
  isIP4 ${VerbIPv4}
  isIP6 ${VerbIPv6}
  if [ "${isIP4}" = "true" ]; then
    /usr/bin/echo "Check host with IPv4"
    checkHost4="$(/usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv4} -p ${VerbPort} -i /root/.ssh/${SSHKey} hostname)"
  else
    /usr/bin/echo "Non-IPv4"
  fi
  if [ "${isIP6}" = "true" ]; then
    /usr/bin/echo "Check host with IPv6"
    checkHost5="$(/usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv6} -p ${VerbPort} -i /root/.ssh/${SSHKey} hostname)"
  else
    /usr/bin/echo "Non-IPv6"
  fi
  if [ "${isIP4}" != "true" ] && [ "${isIP6}" != "true" ]; then
    /usr/bin/echo "No valid IP to access Verber."
    unhealthy="true"
  fi
  if [ "${checkHost4}" != "${VerbHostID}.${namespace}.verb.${VerbTLD}" ] && [ "${checkHost6}" != "${VerbHostID}.${namespace}.verb.${VerbTLD}" ]; then
    . /opt/rink/inkdnsnameservers
    if [ "${checkHost}" = "${VerbHostID}.${BaseHostNS}" ]; then
      /usr/bin/echo "Nameserver: ${checkHost}"
    elif [ "${checkHost}" = "${VerbHostID}.${BaseHostNS}" ]; then
      /usr/bin/echo "Nameserver: ${checkHost}"
    else
      /usr/bin/echo "Host does not check out."
      unhealthy="true"
    fi
  fi
fi
if [ -z "${VerbName}" ]; then
  /usr/bin/echo "VerbName missing from conf."
  unhealthy="true"
else
  if [ "${VerbName}" != "${namespace}" ]; then
    /usr/bin/echo "User doesn't match."
    unhealthy="true"
  fi
fi
if [ -z "${VerbTLD}" ]; then
  /usr/bin/echo "VerbTLD missing from conf."
  unhealthy="true"
else
  if [ "${VerbTLD}" != "${VerbTLD}" ]; then
    /usr/bin/echo "User doesn't match."
    unhealthy="true"
  fi
fi
if [ -z "${VerbRegion}" ]; then
  /usr/bin/echo "VerbRegion missing from conf."
  unhealthy="true"
else
  if ! /usr/bin/vultr-cli regions list | /usr/bin/grep -q "^${VerbRegion}"; then
    /usr/bin/echo "Region invalid."
    unhealthy="true"
  fi
fi
if [ -z "${VerbUser}" ]; then
  /usr/bin/echo "VerbUser missing from conf."
  unhealthy="true"
else
  if [ "${VerbUser}" != "${vuser}" ]; then
    /usr/bin/echo "User doesn't match."
    unhealthy="true"
  fi
fi
if [ -z "${VerbPort}" ]; then
  /usr/bin/echo "VerbPort missing from conf."
  unhealthy="true"
fi
if [ -z "${VerbNameServersConfig}" ]; then
  /usr/bin/echo "VerbNameServersConfig missing from conf."
  unhealthy="true"
else
  if [ ! -f "/opt/rink/ns/${VerbNameServersConfig}"  ]; then
    /usr/bin/echo "Nameserver conf can't be found."
    unhealthy="true"
  fi
fi
if [ -z "${VerbIPv4}" ]; then
  /usr/bin/echo "VerbIPv4 missing from conf."
  unhealthy="true"
else
  isIP4 ${VerbIPv4}
  if [ "${isIP4}" != "true" ]; then
    /usr/bin/echo "IPv4 invalid."
    unhealthy="true"
  fi
fi
if [ -z "${VerbIPv6}" ]; then
  /usr/bin/echo "VerbIPv6 missing from conf."
  unhealthy="true"
else
  isIP6 ${VerbIPv6}
  if [ "${isIP6}" != "true" ]; then
    /usr/bin/echo "Short IPv6 invalid."
    unhealthy="true"
  fi
fi
if [ -z "${VerbIPv6Exp}" ]; then
  /usr/bin/echo "VerbIPv6Exp missing from conf."
  unhealthy="true"
else
  isIP6 ${VerbIPv6Exp}
  if [ "${isIP6}" != "true" ]; then
    /usr/bin/echo "Expanded IPv6 invalid."
    unhealthy="true"
  fi
fi
if [ -z "${VerbARPAIPv4}" ]; then
  /usr/bin/echo "VerbARPAIPv4 missing from conf."
  unhealthy="true"
else
  IPv4ARPA=$(/usr/bin/echo ${VerbIPv4} | /usr/bin/sed -r 's/^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$/\4.\3.\2.\1.in-addr.arpa/')
  if [ "${VerbARPAIPv4}" != "${IPv4ARPA}" ]; then
    /usr/bin/echo "IPv4 ARPA doesn't match."
    unhealthy="true"
  fi
fi
if [ -z "${VerbARPAIPv6}" ]; then
  /usr/bin/echo "VerbARPAIPv6 missing from conf."
  unhealthy="true"
else
  IPv6ARPA=$(rarpa_ipv6 ${VerbIPv6Exp})
  if [ "${VerbARPAIPv6}" != "${IPv6ARPA}" ]; then
    /usr/bin/echo "IPv6 ARPA doesn't match."
    unhealthy="true"
  fi
fi
if [ -z "${Keyscan}" ]; then
  /usr/bin/echo " missing from conf."
  unhealthy="true"
else
  if [ "${Keyscan}" != "DONE" ]; then
    /usr/bin/echo "Keyscan not done."
    unhealthy="true"
  else
    if ! /opt/rink/run/sshrun ${namespace} ${VerbTLD} ${vuser} "exit 0"; then
      /usr/bin/echo "Verber can't be accessed by normal means."
      unhealthy="true"
    fi
  fi
fi

# See if the instance is still there
/usr/bin/echo "Check information"
if ! /usr/bin/vultr-cli instance get ${VultrInstanceID} > /dev/null 2>&1; then
  /usr/bin/echo "Can't get information."
  unhealthy="true"
fi

# Check nameservers
/usr/bin/echo "Check nameservers"
if ! /usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv6} -p ${VerbPort} -i /root/.ssh/${SSHKey} "/usr/bin/ssh ns1 'exit 0'"; then
  /usr/bin/echo "It can't connect to ${NS1Host}."
  unhealthy="true"
fi
if ! /usr/bin/ssh -T -o StrictHostKeyChecking=yes root@${VerbIPv6} -p ${VerbPort} -i /root/.ssh/${SSHKey} "/usr/bin/ssh ns2 'exit 0'"; then
  /usr/bin/echo "It can't connect to ${NS2Host}."
  unhealthy="true"
fi
if ! /usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/ls /srv/sns/${namespace}-${VerbTLD} > /dev/null 2>&1"; then
  /usr/bin/echo "Not listed on ${NS1Host}."
  unhealthy="true"
fi
if ! /usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/ls /srv/sns/${namespace}-${VerbTLD} > /dev/null 2>&1"; then
  /usr/bin/echo "Not listed on ${NS2Host}."
  unhealthy="true"
fi

## Check ssh configs
/usr/bin/echo "Check SSH config"
if ! /usr/bin/grep -q "${IPv4}" /root/.ssh/known_hosts; then
  /usr/bin/echo "IPv4 not a known host."
  unhealthy="true"
fi
if ! /usr/bin/grep -q "${IPv6Cmp}" /root/.ssh/known_hosts && ! /usr/bin/grep -q "${IPv6Exp}" /root/.ssh/known_hosts; then
  /usr/bin/echo "IPv6 not a known host."
  unhealthy="true"
fi
if ! /usr/bin/grep "^Include" /root/.ssh/config | /usr/bin/grep -q "${namespace}.${VerbTLD}.ssh"; then
  /usr/bin/echo "SSH config not listed."
  unhealthy="true"
fi

# Check settings on Verber
/usr/bin/echo "Check that Verber knows its name and IP"
# /usr/bin/ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=3 -T ${namespace}.${VerbTLD} -p ${VerbPort} -i /root/.ssh/${SSHKey} <<EOS # This shows ssh connection output
/usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -T ${namespace}.${VerbTLD} -p ${VerbPort} -i /root/.ssh/${SSHKey} > /dev/null 2>&1 <<EOS # This hides ssh connection output
/usr/bin/grep -q '^ServerName="${namespace}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerHost="${VerbHostID}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerTLD="${VerbTLD}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerIPv4="${VerbIPv4}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerIPv6="${VerbIPv6}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerExpIPv6="${VerbIPv6Exp}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerARPAIPv4="${VerbARPAIPv4}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerARPAIPv6="${VerbARPAIPv6}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS1DNS="${NS1Host}.${RinkDomain}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS1IPv4="${NS1IPv4}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS1IPv6="${NS1IPv6}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS2DNS="${NA2Host}.${RinkDomain}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS2IPv4="${NS2IPv4}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^ServerNS2IPv6="${NS2IPv6}"' /opt/verb/conf/servernameip || exit 6
/usr/bin/grep -q '^127.0.1.1 ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || exit 6
/usr/bin/grep -q '^${VerbIPv4} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || exit 6
/usr/bin/grep -q '^${VerbIPv6} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || /usr/bin/grep -q '^${VerbIPv6Exp} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || exit 6
exit 0
EOS
if [ "$?" != "0" ]; then
  /usr/bin/echo "Verber doesn't proerly know its own name and IP."
  unhealthy="true"
  /usr/bin/echo "Check details with:"
  /usr/bin/cat <<EOS
ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=3 ${namespace}.${VerbTLD} -p ${VerbPort} -i /root/.ssh/${SSHKey}
grep -q '^ServerName="${namespace}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerHost="${VerbHostID}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerTLD="${VerbTLD}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerIPv4="${VerbIPv4}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerIPv6="${VerbIPv6}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerExpIPv6="${VerbIPv6Exp}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerARPAIPv4="${VerbARPAIPv4}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerARPAIPv6="${VerbARPAIPv6}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS1DNS="${NS1Host}.${RinkDomain}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS1IPv4="${NS1IPv4}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS1IPv6="${NS1IPv6}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS2DNS="${NA2Host}.${RinkDomain}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS2IPv4="${NS2IPv4}"' /opt/verb/conf/servernameip || echo fail
grep -q '^ServerNS2IPv6="${NS2IPv6}"' /opt/verb/conf/servernameip || echo fail
grep -q '^127.0.1.1 ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || echo fail
grep -q '^${VerbIPv4} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || echo fail
grep -q '^${VerbIPv6} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || /usr/bin/grep -q '^${VerbIPv6Exp} ${VerbHostID}.${namespace}.verb.${VerbTLD} ${VerbHostID}' /etc/hosts || echo fail
### Done line by line, any error will output "fail"
EOS
fi

# Check any connected drives
#SRC: /usr/bin/grep -HRl "pen.ink" /opt/rink/conf/drives/*."paper".drive
if /usr/bin/ls /opt/rink/conf/drives/*."${vuser}".drive > /dev/null 2>&1; then
  # put each listed drive's config file (with absolute path) in an array so we can loop through and check each
  driveConfigs=($(/usr/bin/grep -HRl "${namespace}.${VerbTLD}" /opt/rink/conf/drives/*."${vuser}".drive))
  # the variable form ${#driveConfigs[@]} shows how many items in the $driveConfigs array
  if [ "${#driveConfigs[@]}" = "1" ]; then
    /usr/bin/echo "Check the connected drive"
  elif [ "${#driveConfigs[@]}" -gt "1" ]; then
    /usr/bin/echo "Check the ${#driveConfigs[@]} connected drives"
  else
    /usr/bin/echo "No connected drives"
  fi
  if [ "${#driveConfigs[@]}" -gt "0" ]; then
    for drive in ${driveConfigs}; do
      . ${drive}
      /usr/bin/echo "Drive::${DriveNickName}"
      if ! /usr/bin/vultr-cli bs get ${DriveID} > /dev/null 2>&1; then
        /usr/bin/echo "Drive '${DriveNickName}' does not exist."
        unhealthy="true"
      else
        /usr/bin/ssh -o StrictHostKeyChecking=no -o ConnectTimeout=3 -T ${DriveVerber} -p ${VerbPort} -i /root/.ssh/${SSHKey} > /dev/null 2>&1 <<EOS
if [ ! -e "/dev/${DriveDev}" ]; then exit 6; fi
if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then exit 6; fi
/usr/bin/grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
/usr/bin/grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
/usr/bin/grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || exit 6
/usr/bin/grep "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || exit 6
EOS
        if [ "$?" != "0" ]; then
          /usr/bin/echo "Drive '${DriveNickName}' not connected correctly."
          unhealthy="true"
          /usr/bin/echo "Check details with:"
          /usr/bin/cat <<EOS
ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=3 ${namespace}.${VerbTLD} -p ${VerbPort} -i /root/.ssh/${SSHKey}
if [ ! -e "/dev/${DriveDev}" ]; then echo fail; fi
if [ ! -f "/opt/verb/conf/inkdrive/${DriveType}.${DriveName}" ]; then echo fail; fi
grep -q "^Device=${DriveDev}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
grep -q "^Mount=${DriveName}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
grep -q "^Type=${DriveType}" /opt/verb/conf/inkdrive/"${DriveType}"."${DriveName}" || echo fail
grep "^/dev/${DriveDev}1" /etc/fstab | grep -q "/mnt/${DriveName}" || echo fail
### Done line by line, any error will output "fail"
EOS
        fi
      fi
    done
  fi
else
  /usr/bin/echo "No drives for user"
fi
# Finish
if [ -n "${unhealthy}" ] && [ "${unhealthy}" = "true" ]; then
  /usr/bin/echo "Verber is not healthy!"
  exit 6
else
  echo "Verber is healthy."
  exit 0
fi
