#!/bin/bash
#inkVerbRunner! verb.ink

# This upgrades the size and usage plan of an existing Vultr VPS
## Generally, this cannot be reversed


# How to use:
## ./growdrive [verb-namespace] [tld] [user] [new size in GB]

# Eg:
## ./growdrive name ink john 20
## ./growdrive name ink john 100


if [ -z "$5" ]; then
  /usr/bin/echo "Needs namespace, TLD, user plan, region, & snapshot arguments, I quit."
  exit 0
fi

# Defaults
. /opt/rink/rinknames

namespace="$1"
VerbTLD="$2"
vuser="$3"
drivenickname="$4"
newdrivesize="$5"


# Check to see if this drive exists
if [ ! -f /opt/rink/conf/drives/${drivenickname}.${vuser}.drive ]; then
  /usr/bin/echo "Drive '${drivenickname}' for user '${vuser}' does not exist. Can't grow it."
  exit 5
else
  . /opt/rink/conf/drives/${drivenickname}.${vuser}.drive
fi

# See if drive's verber is owned by user
if ! /usr/bin/grep -q "VerbUser=\"${vuser}\"" "/opt/rink/conf/verbers/${DriveVerber}.vrb"; then
  /usr/bin/echo "Drive '${drivenickname}' not owned by user '${vuser}'."
  exit 5
else
  . /opt/rink/conf/verbers/${DriveVerber}.vrb
fi

# Check sizing
if [ "${newdrivesize}" -le "${DriveSize}" ]; then
  /usr/bin/echo "Drive's current size is ${DriveSize}; new size must be larger."
  exit 5
fi

# Upgrade the drive
/usr/bin/vultr-cli bs r ${DriveID} -s="${newdrivesize}" >> /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw 2>> /opt/rink/conf/drives/${drivenickname}.${vuser}.growfail.raw

# Exit status?
e="$?"; if [ "$e" != "0" ]; then
  /usr/bin/echo "Drive upgrade failed"
  exit "$e"
fi

# Did it work?
if [ -f "/opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw" ]; then
  if ! /usr/bin/grep -q "^resized block storage" /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw; then
    if /usr/bin/grep "Please wait at least 60s between block storage upgrades" /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw | /usr/bin/grep -q "^error resizing block storage"; then
      /usr/bin/echo "Wait at least 1 minute between drive upgrades."
      exit 0
    else
      /usr/bin/echo "Something went wrong, start over."
      exit 4
    fi
  else
  /usr/bin/sed -i "s/^resized block storage/### resized block storage/" /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw
  fi
else
  /usr/bin/echo "Upgrade output file does not exist, start over."
  exit 4
fi

# Update the config info
datestamp="$(/usr/bin/date +%Y-%m-%d_%T)"
/usr/bin/echo "# ${datestamp} upgraded to ${newdrivesize}" >> /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw
/usr/bin/vultr-cli bs get ${VultrInstanceID} >> /opt/rink/conf/drives/${drivenickname}.${vuser}.grow.raw
/usr/bin/sed -i "s/DriveSize=.*/DriveSize=\"${newdrivesize}\"/" /opt/rink/conf/drives/${drivenickname}.${vuser}.drive

# Finish
/usr/bin/echo "Drive '${drivenickname}' for Verber '${namespace}.${VerbTLD}' grown to ${newdrivesize} GB."
