#!/bin/bash
#inkVerbRunner! verb.ink

# This accepts and stores the remote key signature of a new IP
## Run this just after creating a new server

# How to use:
## ./keyscan [ verb-namespace ] [ verb-tld ] [ -r - optional re-scan (if scan is already complete, but keys changed) ]

# Eg:
## ./keyscan name ink
## ./keyscan name ink -r


if [ -z "$1" ]; then
  /usr/bin/echo "Need to know namespace and verb tld, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"

if [ -f /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb ]; then
  . /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
  . /opt/rink/ns/${VerbNameServersConfig}
  # Re-scanning?
  if [ -n "$3" ] && [ "$3" = "-r" ]; then
    rescan="true"
    # Remove any old identity keys based on our comment system (not necessary, but removes junk)
    /usr/bin/sed -i "/${VerbIPv4}/d" /root/.ssh/known_hosts
    /usr/bin/sed -i "/${VerbIPv6}/d" /root/.ssh/known_hosts
    /usr/bin/sed -i "/^#${namespace}.${VerbTLD}/,/###${namespace}.${VerbTLD}/d" /root/.ssh/known_hosts
  fi
else
  /usr/bin/echo "No such verber!"
  exit 0
fi

if [ -z "${Keyscan}" ] || [ "${Keyscan}" != "DONE" ] || [ -n "${rescan}" ]; then

  while [ ! -f "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.keyscanned" ]; do
    # Use our comment system
    /usr/bin/echo "#${namespace}.${VerbTLD}" >> /root/.ssh/known_hosts
    # Three hashes is the writer's "final cookie"
    /usr/bin/echo "$(/usr/bin/ssh-keyscan -H -p ${VerbPort} ${VerbIPv4})" >> /root/.ssh/known_hosts
    /usr/bin/echo "$(/usr/bin/ssh-keyscan -H -p ${VerbPort} ${VerbIPv6})" >> /root/.ssh/known_hosts
    /usr/bin/echo "###${namespace}.${VerbTLD}" >> /root/.ssh/known_hosts
    if [ "$?" != "0" ]; then
      /usr/bin/sleep 1
    else
      /usr/bin/ssh -o StrictHostKeyChecking=yes -o ConnectTimeout=5 -q ${namespace}.${VerbTLD} "exit 0"
      if [ "$?" != "0" ]; then
        /usr/bin/sleep 1
      else
        /usr/bin/touch "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.keyscanned"
      fi
    fi
  done
  /usr/bin/rm "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.keyscanned"
  /usr/bin/sed -i '/Keyscan=/d' /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
  /usr/bin/echo 'Keyscan="DONE"' >> /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
else
  /usr/bin/echo "SSH keyscan already complete."
fi
