#!/bin/bash
#inkVerbRunner! verb.ink

# This destroys an existing Vultr VPS, based on Verber namespace and TLD

# How to use:
## ./killvps [verb-namespace] [tld] [user]

# Eg:
## ./killvps name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$vuser\"" "/opt/rink/conf/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

# Config
. /opt/rink/rinknames
. /opt/rink/conf/${namespace}.${VerbTLD}.vrb
. /opt/rink/ns/${VerbNameServersConfig}

# Check
if [ "$?" != "0" ]; then
  /usr/bin/echo "Could not be destroyed! Something's wrong. If you recently created this server, wait a few minutes and try again."
  exit 0
fi

# Remove from known_hosts
[[ -n "${VerbIPv4}" ]] && [[ -n "${VerbPort}" ]] && /usr/bin/sed -i "/\[${VerbIPv4}\]:${VerbPort}/d" /root/.ssh/known_hosts
[[ -n "${VerbIPv4}" ]] && /usr/bin/sed -i "/${VerbIPv4}/d" /root/.ssh/known_hosts

# De-list the NS records
#DEV obsolete, see killdns notes
#/opt/rink/run/killdns ${namespace} ${VerbTLD} ${vuser}

# Remove pub SSH keys from verber
## Do this first so that the verber cannot make any changes while later commands are processed
/opt/rink/run/killverbrinkkeys ${namespace} ${VerbTLD} ${vuser}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Close accounts on NS servers
/opt/rink/run/killverbnsaccounts ${namespace} ${VerbTLD} ${vuser}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Remove records on the rink
/opt/rink/run/killverberrecords ${namespace} ${VerbTLD} ${vuser}
e="$?"; [[ "$e" = "0" ]] || exit "$e"

# Refresh nameservers
/usr/bin/ssh ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/inkdnsrefreshbind
/usr/bin/ssh ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/inkdnsrefreshbind

# Destroy it
/usr/bin/vultr-cli instance delete ${VultrInstanceID}
