#!/bin/bash
#inkVerbRunner! verb.ink

# This de-lists the NS records for a verber from the NS nameservers, which were listed in addvps by the rink ordering the verber to run rinkupdateallverbs
#DEV: This is obsolete because kill vps removes /srv/sns/verber-tld/domains/served/ where these are now stored


# How to use:
## ./killdns [ verb-namespace ] [ verb-tld ] [ user ]

# Eg:
## ./killdns name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! /usr/bin/grep -q "VerbUser=\"${vuser}\"" "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

if [ ! -f "/opt/rink/rinknames" ]; then
  echo "Must be setup with setuprinkns first"
  exit 0
fi

# Get our Rink-NS name settings
. /opt/rink/rinknames

# Verber config
. /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
. /opt/rink/ns/${VerbNameServersConfig}

# Generate the URI list
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
  . /opt/verb/inst/domain.mod.conf
  emailURI="${namespace}.email.${DModBase}"
  oneURI="${namespace}.one.${DModBase}"
  inkURI="${namespace}.ink.${DModBase}"
  blueURI="${namespace}.blue.${DModBase}"
  vipURI="${namespace}.vip.${DModBase}"
  kiwiURI="${namespace}.kiwi.${DModBase}"
  redURI="${namespace}.red.${DModBase}"
else
  emailURI="${namespace}.verb.email"
  oneURI="${namespace}.verb.one"
  inkURI="${namespace}.verb.ink"
  blueURI="${namespace}.verb.blue"
  vipURI="${namespace}.verb.vip"
  kiwiURI="${namespace}.verb.kiwi"
  redURI="${namespace}.verb.red"
fi

# De-list the NS records
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${emailURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${emailURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${oneURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${oneURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${inkURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${inkURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${blueURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${blueURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${vipURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${vipURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${kiwiURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${kiwiURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS1Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${redURI}
/usr/bin/ssh -o StrictHostKeyChecking=yes ${NS2Name}.${RinkVerbTLD} /opt/verb/serfs/killinkdnsslavedns ${redURI}

# Set the Serial No
#DEV This may be legacy dev and not necessary since ns*.inkisaverb.com NS servers are handled manually
# . /opt/verb/conf/siteurilist
# /opt/verb/serfs/inkdnsserial ${hostURI}

# Refresh zones
if [ -f "/opt/verb/conf/inkdnsconf" ]; then
  . /opt/verb/conf/inkdnsconf
  if [ "${InkDNSStat}" = "INSTALLED" ]; then
/opt/verb/serfs/inkdnsrefreshbind; fi; fi
