#!/bin/bash
#inkVerbRunner! verb.ink

# This destroys an existing Vultr VPS, based on Verber namespace and TLD

# How to use:
## ./killvps [verb-namespace] [tld] [user]

# Eg:
## ./killvps name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$vuser\"" "/opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

# Config
. /opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf
. /opt/rink/ns/${VerbNameServersConfig}

# Check
if [ "$?" != "0" ]; then
  /usr/bin/echo "Could not be destroyed! Something's wrong. If you recently created this server, wait a few minutes and try again."
  exit 0
fi

# Remove from known_hosts
[[ -n "${VerbIPv4}" ]] && [[ -n "${VerbPort}" ]] && /usr/bin/sed -i "/\[${VerbIPv4}\]:${VerbPort}/d" /root/.ssh/known_hosts
[[ -n "${VerbIPv4}" ]] && /usr/bin/sed -i "/${VerbIPv4}/d" /root/.ssh/known_hosts


# De-list the NS records
/opt/rink/run/killdns ${namespace} ${VerbTLD} ${vuser}

# Remove pub SSH keys from verber
/opt/rink/run/killverbrinkkeys ${namespace} ${VerbTLD} ${vuser}

# Remove other 
kilverberrecords ${namespace} ${VerbTLD} ${vuser}

# Destroy it
/usr/bin/vultr-cli instance delete ${VultrInstanceID}
