#!/bin/bash
#inkVerbRunner! verb.ink

# This removes SSH keys created with newverbrinkkeys from the controlled verber
## This does NOT removed the accounts on the NS servers created with newverbrinkkeys, for that use killverbnsaccounts so as to handle domains also
## This is used by killvps in the process of complete deletion of that verber's VPS

# How to use:
## ./killverbrinkkeys [ verb-namespace ] [ tld ] [ user ]

# Eg:
## ./killverbrinkkeys name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! /usr/bin/grep -q "VerbUser=\"$vuser\"" "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

# Include the configs
. /opt/rink/rinknames
. /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
. /opt/rink/ns/${VerbNameServersConfig}

# Update servernameip, kill keys (created with newverbrinkkeys)
/usr/bin/ssh -T -o StrictHostKeyChecking=yes ${namespace}.${VerbTLD} <<EOS
/usr/bin/sed -i '/ns1.ssh/d' /root/.ssh/config
/usr/bin/rm -f /root/.ssh/ns1.ssh
/usr/bin/sed -i '/ns2.ssh/d' /root/.ssh/config
/usr/bin/rm -f /root/.ssh/ns2.ssh
/usr/bin/sed -i '/RinkConfigured=.*/d' /opt/verb/conf/servernameip
/usr/bin/rm /root/.ssh/Rink_${VerbTLD}_${namespace}.pub
/usr/bin/rm /root/.ssh/Rink_${VerbTLD}_${namespace}
EOS
e="$?"; [[ "$e" = "0" ]] || exit "$e"
