#!/bin/bash
#inkVerbRunner! verb.ink

# This removes SSH keys created with newverbrinkkeys, both from the controlled verber and the NS rinks

# How to use:
## ./killverbrinkkeys [ verb-namespace ] [ tld ] [ user ]

# Eg:
## ./killverbrinkkeys name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$vuser\"" "/opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

. /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb
. /opt/rink/ns/${VerbNameServersConfig}

# Remove SSH entries
/usr/bin/sed -i "/Include \/opt\/rink\/conf\/${namespace}.${VerbTLD}.ssh/d" /root/.ssh/config
/usr/bin/rm -f /opt/rink/conf/verbers/${namespace}.${VerbTLD}.ssh

# Move old conf files to archives
datestamp="$(/usr/bin/date +%Y-%m-%d_%T)"
/usr/bin/mv /opt/rink/conf/verbers/${namespace}.${VerbTLD}.vrb /opt/rink/conf/verbers.destroyed/${vuser}.${namespace}.${VerbTLD}.${datestamp}.vrb
/usr/bin/mv /opt/rink/conf/verbers/${namespace}.${VerbTLD}.raw /opt/rink/conf/verbers.destroyed/${vuser}.${namespace}.${VerbTLD}.${datestamp}.raw
/usr/bin/mv /opt/rink/conf/verbers/${namespace}.${VerbTLD}.srv /opt/rink/conf/verbers.destroyed/${vuser}.${namespace}.${VerbTLD}.${datestamp}.srv

# Remove all SSH identity keys based on our comment system (not necessary, but removes junk)
/usr/bin/sed -i "/${VerbIPv4}/d" /root/.ssh/known_hosts
/usr/bin/sed -i "/${VerbIPv6}/d" /root/.ssh/known_hosts
/usr/bin/sed -i "/^#${namespace}.${VerbTLD}/,/###${namespace}.${VerbTLD}/d" /root/.ssh/known_hosts
