#!/bin/bash
#inkVerbRunner! verb.ink

# This removes SSH keys created with newverbrinkkeys, both from the controlled verber and the NS rinks

# How to use:
## ./killverbrinkkeys [ verb-namespace ] [ tld ] [ user ]

# Eg:
## ./killverbrinkkeys name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

NAMESPACE="$1"
VerbTLD="$2"
USER="$3"

if [ ! -f "/opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf" ]; then
  /usr/bin/echo "${NAMESPACE}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$USER\"" "/opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf"; then
  /usr/bin/echo "${NAMESPACE}.${VerbTLD} not owned by user ${USER}! I quit."
  exit 0
fi

. /opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf

# Remove SSH entries
/usr/bin/sed -i "/Include \/opt\/rink\/conf\/ssh.${NAMESPACE}.${VerbTLD}.conf/d" /root/.ssh/config
/usr/bin/rm -f /opt/rink/conf/ssh.${NAMESPACE}.${VerbTLD}.conf

# Move old conf files to archives
datestamp="$(/usr/bin/date +%Y-%m-%d_%T)"
/usr/bin/mv /opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf /opt/rink/destroyed/vrb.${USER}.${NAMESPACE}.${VerbTLD}.${datestamp}.conf
/usr/bin/mv /opt/rink/conf/raw.${NAMESPACE}.${VerbTLD}.conf /opt/rink/destroyed/raw.${USER}.${NAMESPACE}.${VerbTLD}.${datestamp}.conf

# Remove all SSH identity keys based on our comment system (not necessary, but removes junk)
/usr/bin/sed -i "/${VerbIPv4}/d" /root/.ssh/known_hosts
/usr/bin/sed -i "/${VerbIPv6}/d" /root/.ssh/known_hosts
/usr/bin/sed -i "/^#${NAMESPACE}.${VerbTLD}/,/###${NAMESPACE}.${VerbTLD}/d" /root/.ssh/known_hosts
