#!/bin/bash
#inkVerbRunner! verb.ink

# This creates SSH keys on a newly-creaed controlled verber and adds them to the NS rinks
## This must be run AFTER verb/inst/preverboff (if applicable), but BEFORE verb/inst/setup on the new verber
## This is used by addvps
## This is undone by killverbrinkkeys and killverbnsaccounts

# How to use:
## ./newverbrinkkeys [verb-namespace] [tld] [user]

# Eg:
## ./newverbrinkkeys name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

# Rink config
. /opt/rink/rinknames

namespace="$1"
VerbTLD="$2"
vuser="$3"

if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$vuser\"" "/opt/rink/conf/${namespace}.${VerbTLD}.vrb"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
  exit 0
fi

## Include the configs
. /opt/rink/portnum
. /opt/verb/conf/servernameip
. /opt/rink/sshkey
. /opt/rink/conf/${namespace}.${VerbTLD}.vrb
. /opt/rink/rinknames

#DEV these keys should already be accepted
# if [ -z "${FIRSTSSH}" ]; then
#   /usr/bin/-o StrictHostKeyChecking=accept-new ${namespace}.${VerbTLD} cat /etc/ssh/ssh_host_dsa_key.pub >> ~/.ssh/known_hosts
#   if [ "$?" = "0" ]; then
#     /usr/bin/echo "FIRSTSSH=\"true\"" >> /opt/rink/conf/${namespace}.${VerbTLD}.vrb
#   fi
# fi

# Setup on the controlled verber
/usr/bin/ssh ${namespace}.${VerbTLD} "/usr/bin/ssh-keygen -t rsa -N '' -f /root/.ssh/Rink_${VerbTLD}_${namespace} -C Rink_${VerbTLD}_${namespace}"
/usr/bin/ssh ${namespace}.${VerbTLD} /usr/bin/cat /root/.ssh/Rink_${VerbTLD}_${namespace}.pub > /opt/rink/tmp/Rink_${VerbTLD}_${namespace}.pub
/usr/bin/ssh ${namespace}.${VerbTLD} /usr/bin/cat /opt/verb/conf/servertldstatus286 > /opt/rink/tmp/servertldstatus_${VerbTLD}_${namespace}

## NS 1, NS 2, servernameip
. /opt/rink/ns/${NameServersConfig}
/usr/bin/ssh -T ${namespace}.${VerbTLD} <<EOS
/usr/bin/touch /root/.ssh/config

/usr/bin/sed -i '/ns1.ssh/d' /root/.ssh/config
/usr/bin/rm -f /root/.ssh/ns1.ssh
/usr/bin/echo 'Include /root/.ssh/ns1.ssh' >> /root/.ssh/config
/usr/bin/cat <<EOF > /root/.ssh/ns1.ssh
Host ns1
Hostname ${ServerNS1IPv4}
User ${namespace}-${VerbTLD}
Port ${Port}
IdentityFile /root/.ssh/Rink_${VerbTLD}_${namespace}
EOF
/usr/bin/echo "#ns1" >> /root/.ssh/known_hosts
/usr/bin/ssh-keyscan -H -p ${Port} ${ServerNS1IPv4} >> /root/.ssh/known_hosts
/usr/bin/echo "###ns1" >> /root/.ssh/known_hosts

/usr/bin/sed -i '/ns2.ssh/d' /root/.ssh/config
/usr/bin/rm -f /root/.ssh/ns2.ssh
/usr/bin/echo 'Include /root/.ssh/ns2.ssh' >> /root/.ssh/config
/usr/bin/cat <<EOF > /root/.ssh/ns2.ssh
Host ns2
Hostname ${ServerNS2IPv4}
User ${namespace}-${VerbTLD}
Port ${Port}
IdentityFile /root/.ssh/Rink_${VerbTLD}_${namespace}
EOF
/usr/bin/echo "#ns2" >> /root/.ssh/known_hosts
/usr/bin/ssh-keyscan -H -p ${Port} ${ServerNS2IPv4} >> /root/.ssh/known_hosts
/usr/bin/echo "###ns2" >> /root/.ssh/known_hosts

/usr/bin/chmod 700 /root/.ssh
/usr/bin/chmod 644 /root/.ssh/Rink_${VerbTLD}_${namespace}.pub
/usr/bin/chmod 600 /root/.ssh/Rink_${VerbTLD}_${namespace}
/usr/bin/chmod 600 /root/.ssh/config
/usr/bin/chmod 600 /root/.ssh/ns1.ssh
/usr/bin/chmod 600 /root/.ssh/ns2.ssh

/usr/bin/sed -i '/RinkConfigured=.*/d' /opt/verb/conf/servernameip286
/usr/bin/echo 'RinkConfigured="true"' >> /opt/verb/conf/servernameip286
EOS

# Setup on the NS nameservers
. /opt/rink/ns/${VerbNameServersConfig}
/usr/bin/ssh -T ${NS1Name}.${RinkVerbTLD} <<EOS
/usr/bin/groupadd ${namespace}-${VerbTLD}
/usr/bin/useradd -g ${namespace}-${VerbTLD} ${namespace}-${VerbTLD}
/usr/bin/mkdir -p /srv/sns/${namespace}-${VerbTLD}/.ssh /srv/sns/${namespace}-${VerbTLD}/domains/served /srv/sns/${namespace}-${VerbTLD}/domains/parked
/usr/bin/usermod -d /srv/sns/${namespace}-${VerbTLD} ${namespace}-${VerbTLD}
/usr/bin/cat <<EOF > /srv/sns/${namespace}-${VerbTLD}/conf
VerbHostID="${VerbHostID}"
VerbName="${VerbName}"
VerbTLD="${VerbTLD}"
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
/usr/bin/chown -R ${namespace}-${VerbTLD}:${namespace}-${VerbTLD} /srv/sns/${namespace}-${VerbTLD}
/usr/bin/chmod 700 /srv/sns/${namespace}-${VerbTLD}/.ssh
EOS
/usr/bin/ssh -T ${NS2Name}.${RinkVerbTLD} <<EOS
/usr/bin/groupadd ${namespace}-${VerbTLD}
/usr/bin/useradd -g ${namespace}-${VerbTLD} ${namespace}-${VerbTLD}
/usr/bin/mkdir -p /srv/sns/${namespace}-${VerbTLD}/.ssh /srv/sns/${namespace}-${VerbTLD}/domains/served /srv/sns/${namespace}-${VerbTLD}/domains/parked
/usr/bin/usermod -d /srv/sns/${namespace}-${VerbTLD} ${namespace}-${VerbTLD}
/usr/bin/cat <<EOF > /srv/sns/${namespace}-${VerbTLD}/conf
VerbHostID="${VerbHostID}"
VerbName="${VerbName}"
VerbTLD="${VerbTLD}"
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
/usr/bin/chown -R ${namespace}-${VerbTLD}:${namespace}-${VerbTLD} /srv/sns/${namespace}-${VerbTLD}
/usr/bin/chmod 700 /srv/sns/${namespace}-${VerbTLD}/.ssh
EOS

# Update user directories with settings and ssh keys
. /opt/rink/ns/${VerbNameServersConfig}
/usr/bin/cat /opt/rink/tmp/Rink_${VerbTLD}_${namespace}.pub | /usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/cat > /srv/sns/${namespace}-${VerbTLD}/.ssh/authorized_keys"
/usr/bin/cat /opt/rink/tmp/Rink_${VerbTLD}_${namespace}.pub | /usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/cat > /srv/sns/${namespace}-${VerbTLD}/.ssh/authorized_keys"
/usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/chmod 600 /srv/sns/${namespace}-${VerbTLD}/.ssh/authorized_keys"
/usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/chmod 600 /srv/sns/${namespace}-${VerbTLD}/.ssh/authorized_keys"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${VerbTLD}_${namespace} | /usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/cat > /srv/sns/${namespace}-${VerbTLD}/servertldstatus"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${VerbTLD}_${namespace} | /usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/cat > /srv/sns/${namespace}-${VerbTLD}/servertldstatus"
/usr/bin/ssh ${NS1Name}.${RinkVerbTLD} "/usr/bin/chown -R ${namespace}-${VerbTLD}:${namespace}-${VerbTLD} /srv/sns/${namespace}-${VerbTLD}"
/usr/bin/ssh ${NS2Name}.${RinkVerbTLD} "/usr/bin/chown -R ${namespace}-${VerbTLD}:${namespace}-${VerbTLD} /srv/sns/${namespace}-${VerbTLD}"
/usr/bin/rm -f /opt/rink/tmp/Rink_${VerbTLD}_${namespace}.pub
/usr/bin/rm -f /opt/rink/tmp/servertldstatus_${VerbTLD}_${namespace}

# Note in the settings
/usr/bin/echo 'RinkKeys="DONE"' >> /opt/rink/conf/${namespace}.${VerbTLD}.vrb
