#!/bin/bash
#inkVerbRunner! verb.ink

# This waits until a VPS is powered on according to the POWER STATUS from vultr-cli instance get

# How to use:
## ./powervpson [verb-namespace] [tld]

# Eg:
## ./powervpson name ink


if [ -z "$2" ]; then
  /usr/bin/echo "Needs namespace & TLDarguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"

if [ ! -f "/opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

. /opt/rink/conf/vrb.${namespace}.${VerbTLD}.conf

# Wait for powerup
powerstatus="$(/usr/bin/vultr-cli instance get $VultrInstanceID | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
while [ "$powerstatus" != "running" ]; do
  /usr/bin/vultr-cli instance poweron ${VultrInstanceID}
  sleep 5
  powerstatus="$(/usr/bin/vultr-cli instance get $VultrInstanceID | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
done
