#!/bin/bash
#inkVerbRunner! verb.ink

# This restarts an existing Vultr VPS, based on Verber namespace and TLD

# How to use:
## ./restartvps [verb-namespace] [tld] [user]

# Eg:
## ./restartvps name ink john


if [ -z "$3" ]; then
  /usr/bin/echo "Needs namespace, TLD & user arguments, I quit."
  exit 0
fi

NAMESPACE="$1"
VerbTLD="$2"
USER="$3"

if [ ! -f "/opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf" ]; then
  /usr/bin/echo "${NAMESPACE}.${VerbTLD} does not exist! I quit."
  exit 0
fi

if ! grep -q "VerbUser=\"$USER\"" "/opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf"; then
  /usr/bin/echo "${NAMESPACE}.${VerbTLD} not owned by user ${USER}! I quit."
  exit 0
fi

. /opt/rink/conf/vrb.${NAMESPACE}.${VerbTLD}.conf

/usr/bin/echo "Restarting. This may take a few minutes..."

/usr/bin/vultr-cli instance restart ${VultrInstanceID}

# Finish
/usr/bin/echo "${NAMESPACE}.${VerbTLD} restarted. It may take a few minutes for all services to become available."
