#!/bin/bash
#inkVerbRunner! verb.ink

# This sets the new snapshot ID

# How to use:
## ./setsnapshot [ snapshotID ] [ nickname ]

# Eg:
## ./setsnapshot somelongkey laemp


if [ -z "$2" ]; then
  /usr/bin/echo "Needs snapshot ID & nickname as arguments, I quit."
  exit 0
fi

NewSnapshotID="$1"
nickname="$2"

/usr/bin/cat <<EOF > /opt/rink/snapshotid/${nickname}
SnapshotID="$NewSnapshotID"
EOF
