#!/bin/bash
#inkVerbRunner! verb.ink

# This creates and connects this Rink with the two main NS servers
## Prerequesite: setrinknames, setkey, setport, setsnapshot, setup
## Prerequesite: setup must NOT be run yet!
## This runs setup for all three servers, including this one

# How to use:
## ./setuprinkns


if [ ! -f "/opt/rink/rinknames" ]; then
  echo "Must run setrinknames first"
  exit 0
fi

if [ -f "/opt/rink/.configured" ]; then
  echo "Already configured, you'll need to hack some to run this again"
  exit 0
fi

# Get our Rink-NS name settings
. /opt/rink/rinknames
. /opt/rink/portnum

# Custom NS regions?


# In progress or from start?
if [ ! -f "/opt/rink/waitnsfinish" ]; then
  # Run setup files, checking progress at each step of the way
  if [ -f "/opt/verb/inst/make-dns" ]; then
    /opt/verb/inst/make-dns ${RinkHost} ${RinkDomain}; fi
  if [ -f "/opt/verb/inst/setup" ]; then
    /opt/verb/inst/setup ${RinkName} ${RinkVerbTLD} email vip ${RinkHost} ${RinkIPv4} ${RinkIPv6} cb@${RinkDomain} 100 1000 ${TimeZone} ${Port} boss "$(/usr/bin/pwgen -s -1 16)" ${UpdateRepo} ${UpdateOrg};fi
  # Create the NS nameservers
  if [ ! -f "/opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf" ]; then
  /opt/rink/run/newvps ${NS1Name} ${RinkVerbTLD} byrink 1gb ${DfaultNSSnapshotID} ${VultrRegion1}; fi
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  # Check if finished right
  if ! /usr/bin/grep -q ^VerbIPv4 /opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf; then
    /usr/bin/echo "NS1 was not created correctly. Run this again to try again."
    /usr/bin/rm -f "*.${NS1Name}.${RinkVerbTLD}.conf"
    /usr/bin/sed -i "/ssh.${NS1Name}.${RinkVerbTLD}.conf/d" /root/.ssh/config
    exit 0; fi
  if [ ! -f "/opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf" ]; then
  /opt/rink/run/newvps ${NS2Name} ${RinkVerbTLD} byrink 1gb ${DfaultNSSnapshotID} ${VultrRegion2}; fi
  e="$?"; [[ "$e" = "0" ]] || exit "$e"
  # Check if finished right
  if ! /usr/bin/grep -q ^VerbIPv4 /opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf; then
    /usr/bin/echo "NS2 was not created correctly. Run this again to try again."
    /usr/bin/rm -f "*.${NS2Name}.${RinkVerbTLD}.conf"
    /usr/bin/sed -i "/ssh.${NS2Name}.${RinkVerbTLD}.conf/d" /root/.ssh/config
    exit 0; fi
  # Wait for servers to finish
  /usr/bin/touch /opt/rink/waitnsfinish
  /usr/bin/echo "Waiting for NS servers to finish creation; re-run this script if it times-out to continue from this stage"
fi

# NS1
if [ ! -f "/opt/rink/ns1done" ]; then
## Try to add keys until added
  . /opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf
  ### Wait for powerup
  /opt/rink/run/waitvpson ${NS1Name} ink
  #DEV keyscan is a native part of newvps
  # while [ ! -f "/opt/rink/ns1added" ]; do
  #   /opt/rink/run/keyscan ${NAMESPACE} ${VerbTLD}
  #   #/usr/bin/ssh-keyscan -H -p ${VerbPort} ${VerbIPv4} >> /root/.ssh/known_hosts
  #   wait
  #   if [ "$?" != "0" ]; then
  #     /usr/bin/sleep 1
  #   else
  #     /usr/bin/touch /opt/rink/ns1added
  #   fi
  # done
  ## Setup
  /usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/inst/make-dns ${NS1Host} ${RinkDomain}
  wait
  /usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/setup ${NS1Name} ${RinkVerbTLD} email vip ${NS1Host} ${VerbIPv4} ${VerbIPv6} cb@${RinkDomain} 100 1000 ${TimeZone1} ${VerbPort} boss "$(/usr/bin/pwgen -s -1 16)" ${UpdateRepo} ${UpdateOrg}
  wait
  if [ "$?" = "0" ]; then
    /usr/bin/touch /opt/rink/ns1done
  else
    /usr/bin/echo "NS1 can't run setup"
    exit 0
  fi
fi

# NS2
if [ ! -f "/opt/rink/ns2done" ]; then
  ## Try to add keys until added
  . /opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf
  ### Wait for powerup
  /opt/rink/run/waitvpson ${NS2Name} ink
  #DEV keyscan is a native part of newvps
  # while [ ! -f "/opt/rink/ns2added" ]; do
  #   /opt/rink/run/keyscan ${NAMESPACE} ${VerbTLD}
  #   #/usr/bin/ssh-keyscan -H -p ${VerbPort} ${VerbIPv4} >> /root/.ssh/known_hosts
  #   wait
  #   if [ "$?" != "0" ]; then
  #     /usr/bin/sleep 1
  #   else
  #     /usr/bin/touch /opt/rink/ns2added
  #   fi
  # done
  ## Setup
  /usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/inst/make-dns ${NA2Host} ${RinkDomain}
  wait
  /usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/setup ${NS2Name} ${RinkVerbTLD} email vip ${NA2Host} ${VerbIPv4} ${VerbIPv6} cb@${RinkDomain} 100 1000 ${TimeZone2} ${VerbPort} boss "$(/usr/bin/pwgen -s -1 16)" ${UpdateRepo} ${UpdateOrg}
  wait
  if [ "$?" = "0" ]; then
    /usr/bin/touch /opt/rink/ns2done
  else
    /usr/bin/echo "NS2 can't run setup"
    exit 0
  fi
fi

# Update our global NS nameservers
. /opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf
NS1ip4="$VerbIPv4"
NS1ip6="$VerbIPv6"
. /opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf
NS2ip4="$VerbIPv4"
NS2ip6="$VerbIPv6"
## Point the NS servers to each other
### NS1
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnssetrink "${NA2Host}.${RinkDomain}" "${NS2ip4}" "${NS2ip6}"
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnssetrink2 "${RinkHost}.${RinkDomain}" "${RinkIPv4}" "${RinkIPv6}"
### NS2
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnssetrink "${NS1Host}.${RinkDomain}" "${NS1ip4}" "${NS1ip6}"
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnssetrink2 "${RinkHost}.${RinkDomain}" "${RinkIPv4}" "${RinkIPv6}"
### This nameserver uses the normal other two, but must be set manually because it is a NS server via make-dns
/opt/verb/serfs/inkdnssetrink "${NS1Host}.${RinkDomain}" "${NS1ip4}" "${NS1ip6}"
/opt/verb/serfs/inkdnssetrink2 "${NA2Host}.${RinkDomain}" "${NS2ip4}" "${NS2ip6}"

# Install DNS & Certs that DNS servers skip in setup
## Rink
/opt/verb/serfs/inkdnsinstall; wait
/opt/verb/serfs/inkcertinstall; wait
/opt/verb/serfs/setsecure; wait
## NS1
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsinstall; wait
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkcertinstall; wait
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/setsecure; wait
## NS2
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsinstall; wait
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkcertinstall; wait
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/setsecure; wait
## Servers up?
/opt/rink/run/waitvpsanswer ${NS1Name} ${VerbTLD}
/opt/rink/run/waitvpsanswer ${NS2Name} ${VerbTLD}

# Notification
/usr/bin/echo "Disabling the DNS service, you may see some error messages during setup which can be ignored..."

# Site URIlist
. /opt/verb/conf/siteurilist # Only for $hostURI
if [ -f "/opt/verb/inst/domain.mod.conf" ]; then
  . /opt/verb/inst/domain.mod.conf
  emailBASE="email.${DModBase}"
  oneBASE="one.${DModBase}"
  inkBASE="ink.${DModBase}"
  blueBASE="blue.${DModBase}"
  vipBASE="vip.${DModBase}"
  kiwiBASE="kiwi.${DModBase}"
  redBASE="red.${DModBase}"
else
  emailBASE="verb.email"
  oneBASE="verb.one"
  inkBASE="verb.ink"
  blueBASE="verb.blue"
  vipBASE="verb.vip"
  kiwiBASE="verb.kiwi"
  redBASE="verb.red"
fi

# Host Rink verb.tld list on all three NS servers

## Dirs used by inkdnsaddslave
### Rink on NS1
. /opt/verb/conf/servernameip
/usr/bin/ssh ${NS1Name}.${VerbTLD} <<EOS
/usr/bin/mkdir -p /srv/sns/${RinkName}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${RinkName}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
EOS
### NS2 on NS1
. /opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf
/usr/bin/ssh ${NS1Name}.${VerbTLD} <<EOS
/usr/bin/mkdir -p /srv/sns/${NS2Name}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${NS2Name}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
EOS
### Rink on NS2
. /opt/verb/conf/servernameip
/usr/bin/ssh ${NS2Name}.${VerbTLD} <<EOS
/usr/bin/mkdir -p /srv/sns/${RinkName}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${RinkName}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
EOS
### NS1 on NS2 
. /opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf
/usr/bin/ssh ${NS2Name}.${VerbTLD} <<EOS
/usr/bin/mkdir -p /srv/sns/${NS1Name}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${NS1Name}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
EOS
### NS1 on this local Rink
. /opt/rink/conf/vrb.${NS1Name}.${RinkVerbTLD}.conf
/usr/bin/mkdir -p /srv/sns/${NS1Name}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${NS1Name}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF
### NS2 on this local Rink
. /opt/rink/conf/vrb.${NS2Name}.${RinkVerbTLD}.conf
/usr/bin/mkdir -p /srv/sns/${NS2Name}-${VerbTLD}/domains
/usr/bin/cat <<EOF > /srv/sns/${NS2Name}-${VerbTLD}/conf
VerbIPv4="${VerbIPv4}"
VerbIPv6="${VerbIPv6}"
VerbIPv6Exp="${VerbIPv6Exp}"
VerbARPAIPv4="${VerbARPAIPv4}"
VerbARPAIPv6="${VerbARPAIPv6}"
EOF

## Configs
### Fetch from all
/usr/bin/ssh ${NS1Name}.${VerbTLD} /usr/bin/cat /opt/verb/conf/servertldstatus > /opt/rink/tmp/servertldstatus_${NS1Name}_${VerbTLD}
/usr/bin/ssh ${NS2Name}.${VerbTLD} /usr/bin/cat /opt/verb/conf/servertldstatus > /opt/rink/tmp/servertldstatus_${NS2Name}_${VerbTLD}
/usr/bin/cat /opt/verb/conf/servertldstatus > /opt/rink/tmp/servertldstatus_${RinkName}_${VerbTLD}
### Write to all
/usr/bin/cat /opt/rink/tmp/servertldstatus_${NS2Name}_${VerbTLD} | /usr/bin/ssh ${NS1Name}.${VerbTLD} "/usr/bin/cat > /srv/sns/${NS2Name}-${VerbTLD}/servertldstatus"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${RinkName}_${VerbTLD} | /usr/bin/ssh ${NS1Name}.${VerbTLD} "/usr/bin/cat > /srv/sns/${RinkName}-${VerbTLD}/servertldstatus"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${NS1Name}_${VerbTLD} | /usr/bin/ssh ${NS2Name}.${VerbTLD} "/usr/bin/cat > /srv/sns/${NS1Name}-${VerbTLD}/servertldstatus"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${RinkName}_${VerbTLD} | /usr/bin/ssh ${NS2Name}.${VerbTLD} "/usr/bin/cat > /srv/sns/${RinkName}-${VerbTLD}/servertldstatus"
/usr/bin/cat /opt/rink/tmp/servertldstatus_${NS1Name}_${VerbTLD} > /srv/sns/${NS1Name}-${VerbTLD}/servertldstatus
/usr/bin/cat /opt/rink/tmp/servertldstatus_${NS2Name}_${VerbTLD} > /srv/sns/${NS2Name}-${VerbTLD}/servertldstatus
/usr/bin/rm -f /opt/rink/tmp/*

## NS1
### Add slave domains for Rink
/usr/bin/ssh ${NS1Name}.${VerbTLD} /usr/bin/systemctl stop named
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${inkBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${emailBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${oneBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${blueBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${vipBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${redBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${kiwiBASE} -n
### Add slave domains for NS2
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${inkBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${emailBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${oneBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${blueBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${vipBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${redBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${kiwiBASE} -n
/usr/bin/ssh ${NS1Name}.${VerbTLD} /usr/bin/systemctl start named
if /usr/bin/ssh ${NS1Name}.${VerbTLD} /usr/bin/systemctl is-active --quiet named; then
  echo "NS1 DNS service is working, you may ignore any above 'named' error messages"
fi
/usr/bin/ssh ${NS1Name}.${VerbTLD} /opt/verb/serfs/inkdnsrefreshbind

## NS2
### Add slave domains for Rink
/usr/bin/ssh ${NS2Name}.${VerbTLD} /usr/bin/systemctl stop named
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${inkBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${emailBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${oneBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${blueBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${vipBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${redBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${RinkName}-${VerbTLD} ${RinkName}.${kiwiBASE} -n
### Add slave domains for NS1
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${inkBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${emailBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${oneBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${blueBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${vipBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${redBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${kiwiBASE} -n
/usr/bin/ssh ${NS2Name}.${VerbTLD} /usr/bin/systemctl start named
if /usr/bin/ssh ${NS2Name}.${VerbTLD} /usr/bin/systemctl is-active --quiet named; then
  echo "NS2 DNS service is working, you may ignore any above 'named' error messages"
fi
/usr/bin/ssh ${NS2Name}.${VerbTLD} /opt/verb/serfs/inkdnsrefreshbind

## This local Rink server
/usr/bin/systemctl stop named
### Add slave domains for NS1
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${inkBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${emailBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${oneBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${blueBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${vipBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${redBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS1Name}-${VerbTLD} ${NS1Name}.${kiwiBASE} -n
### Add slave domains for NS2
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${inkBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${emailBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${oneBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${blueBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${vipBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${redBASE} -n
/opt/verb/serfs/inkdnsaddslave ${NS2Name}-${VerbTLD} ${NS2Name}.${kiwiBASE} -n
/usr/bin/systemctl start named
if /usr/bin/systemctl is-active --quiet named; then
  echo "The Rink DNS service is working, you may ignore any above 'named' error messages"
fi
/opt/verb/serfs/inkdnsrefreshbind

# Display what the inklist file should be
/usr/bin/cat <<EOF > /opt/verb/conf/inklists/inkdnsrinks
BaseHostNS="${RinkDomain}"
DefaultNS1="${NS1Host}.${RinkDomain}"
RinkNS1IPv4="${NS1ip4}"
RinkNS1IPv6="${NS1ip6}"
DefaultNS2="${NA2Host}.${RinkDomain}"
RinkNS2IPv4="${NS2ip4}"
RinkNS2IPv6="${NS2ip6}"
EOF

# Reboot NS servers
/usr/bin/ssh ${NS1Name}.${VerbTLD} reboot
/usr/bin/ssh ${NS2Name}.${VerbTLD} reboot

# Finish
/usr/bin/echo "
The inkDNS nameservers are now set. This should be updated in the public verb repo...

verb/conf/inklists/inkdnsrinks :
"

/usr/bin/cat /opt/verb/conf/inklists/inkdnsrinks
cp /opt/verb/conf/inklists/inkdnsrinks /opt/rink/inkdnsrinks

/usr/bin/echo "
###

Cheers!
Last step in this setup Rink: reboot"

# Cleanup
/usr/bin/rm -f /opt/rink/ns1done
/usr/bin/rm -f /opt/rink/ns2done
/usr/bin/rm -f /opt/rink/ns1added
/usr/bin/rm -f /opt/rink/ns2added
/usr/bin/rm -f /opt/rink/waitnsfinish
/usr/bin/echo 'LASTID="1000"' > /opt/rink/lastverbid
/usr/bin/touch /opt/rink/.configured
