#!/bin/bash
#inkVerbRunner! verb.ink

# This disconnects a drive from its connected VPS
## verb namespace and verb TLD are needed for security only

# How to use:
## ./unplugdrive [verb-namespace] [tld] [user] [drive-nickname]

# Eg:
## ./unplugdrive name ink someuser twentyhard
## ./unplugdrive blink ink johnuser tensolid

# Get our Rink-NS name settings
. /opt/rink/rinknames

namespace="$1"
VerbTLD="$2"
vuser="$3"
drivenickname="$4"

# Credential checks
if [ -z "${4}" ]; then
  /usr/bin/echo "Enter all credentials; read instructions."
  exit 5
fi

if [ ! -f "/opt/rink/drive/${drivenickname}.${vuser}.drive" ]; then
  /usr/bin/echo "Drive does not exist for this user! I quit."
  exit 5
else
  . "/opt/rink/drive/${drivenickname}.${vuser}.drive"
fi

if grep -q "DriveDev=\"UNPLUGGED\"" "/opt/rink/drive/${drivenickname}.${vuser}.drive"; then
  /usr/bin/echo "Drive ${drivenickname} is already unplugged yet! Nothing to do."
  exit 0
fi

if ! grep -q "DriveNickName=\"${drivenickname}\"" "/opt/rink/drive/${drivenickname}.${vuser}.drive"; then
  /usr/bin/echo "Drive ${drivenickname} nickname doesn't match up! Something is very wrong."
  exit 6
fi

if ! grep -q "DriveVerber=\"${namespace}.${VerbTLD}\"" "/opt/rink/drive/${drivenickname}.${vuser}.drive"; then
  /usr/bin/echo "${namespace}.${VerbTLD} not assigned to drive ${drivenickname}! I quit."
  exit 5
fi

# DEV available variables
# ${DriveID}
# ${DriveNickName}
# ${DriveVerber}
# ${DriveName}
# ${DriveType}
# ${DriveSize}
# ${DriveRegion}
# ${DriveDev}

# Unmount the drive on the verber if the verber exists
if [ -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
  if ! grep -q "VerbUser=\"${vuser}\"" "/opt/rink/conf/${namespace}.${VerbTLD}.vrb"; then
    /usr/bin/echo "${namespace}.${VerbTLD} not owned by user ${vuser}! I quit."
    exit 5
  else
    /usr/bin/ssh ${namespace}.${VerbTLD} /opt/verb/serfs/inkdrivekill ${DriveDev} ${DriveName} ${DriveType} ignore
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
    # Disconnect the drive
    /usr/bin/vultr-cli bs detach ${DriveID}
    e="$?"; [[ "$e" = "0" ]] || exit "$e"
  fi
else
  # The VPS must have been destroyed before this drive was unplugged, let's get our records up to date anyway (detaching would create an error since that happened at VPS destruction)
  /usr/bin/echo "Drive ${DriveNickName} isn't attached to anything. Finishing the unplug process..."
fi

# Records
datestamp="$(/usr/bin/date +%Y-%m-%d_%T)"
/usr/bin/cp /opt/rink/drive/${DriveNickName}.${vuser}.drive /opt/rink/smashed/${vuser}.${DriveNickName}.${datestamp}.unplugged
/usr/bin/echo "DriveUnplugged=\"${datestamp}\"" >> /opt/rink/smashed/${vuser}.${DriveNickName}.${datestamp}.unplugged

# Update the config
/usr/bin/sed -i "s/DriveDev=.*/DriveDev=\"UNPLUGGED\"/" /opt/rink/drive/${DriveNickName}.${vuser}.drive

# Finish
/usr/bin/echo "Drive ${DriveName} unplugged from ${DriveVerber}"
