#!/bin/bash
#inkVerbRunner! verb.ink

# This waits until a VPS is powered on according to the POWER STATUS from vultr-cli instance get

# How to use:
## ./waitvpson [verb-namespace] [tld]

# Eg:
## ./waitvpson name ink


if [ -z "$2" ]; then
  /usr/bin/echo "Needs namespace & TLDarguments, I quit."
  exit 0
fi

namespace="$1"
VerbTLD="$2"

if [ ! -f "/opt/rink/conf/${namespace}.${VerbTLD}.vrb" ]; then
  /usr/bin/echo "${namespace}.${VerbTLD} does not exist! I quit."
  exit 0
fi

. /opt/rink/conf/${namespace}.${VerbTLD}.vrb
. /opt/rink/ns/${VerbNameServersConfig}

# Wait for powerup
count=0
powerstatus="$(/usr/bin/vultr-cli instance get ${VultrInstanceID} | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
while [ "${powerstatus}" != "running" ]; do
  sleep 5
  powerstatus="$(/usr/bin/vultr-cli instance get ${VultrInstanceID} | /usr/bin/grep '^POWER STATUS' | /usr/bin/sed s"/POWER STATUS\t\t//")"
    # If we have been trying 10 minutes, restart
  if [ "$count" -gt "60" ]; then
    /opt/rink/run/powercycle ${namespace} ${VerbTLD}
    count=0
  fi
  ((count++))
done
